# Generated by Django 4.1.2 on 2022-10-11 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms", name="price", field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="rooms",
            name="room_image",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
