# Generated by Django 4.1.2 on 2022-10-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rooms_price_rooms_room_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="rooms", name="preference_id",),
        migrations.AddField(
            model_name="rooms",
            name="preferences",
            field=models.ManyToManyField(to="home.preferences"),
        ),
    ]
