# Generated by Django 4.1.2 on 2022-10-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_rooms_preference_id_rooms_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="Capacity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cap", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food", models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(name="Host",),
        migrations.RemoveField(model_name="preferences", name="created_at",),
        migrations.RemoveField(model_name="preferences", name="eminity1",),
        migrations.RemoveField(model_name="preferences", name="eminity2",),
        migrations.RemoveField(model_name="preferences", name="eminity3",),
        migrations.RemoveField(model_name="preferences", name="eminity4",),
        migrations.RemoveField(model_name="preferences", name="eminity5",),
        migrations.RemoveField(model_name="preferences", name="eminity6",),
        migrations.RemoveField(model_name="preferences", name="eminity7",),
        migrations.RemoveField(model_name="preferences", name="preferred_cusine",),
        migrations.RemoveField(model_name="preferences", name="room",),
        migrations.RemoveField(model_name="preferences", name="roommate_no",),
        migrations.RemoveField(model_name="preferences", name="updated_at",),
        migrations.AddField(
            model_name="preferences",
            name="name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="rooms",
            name="cap",
            field=models.ManyToManyField(to="home.capacity"),
        ),
        migrations.AddField(
            model_name="rooms",
            name="food",
            field=models.ManyToManyField(to="home.food"),
        ),
        migrations.AddField(
            model_name="rooms",
            name="room_type",
            field=models.ManyToManyField(to="home.room_type"),
        ),
    ]
