# Generated by Django 4.1.2 on 2022-10-18 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_rooms_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="cap",
            field=models.ManyToManyField(
                choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], to="home.capacity"
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="food",
            field=models.ManyToManyField(
                choices=[
                    ("veg", "Vegetarian"),
                    ("non-veg", "Non-vegetarian"),
                    ("none", "none"),
                ],
                to="home.food",
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_type",
            field=models.ManyToManyField(
                choices=[("Shared room", "Shared room"), ("pvt room", "Private room")],
                to="home.room_type",
            ),
        ),
    ]
