# Generated by Django 4.1.2 on 2022-10-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_rooms_cap_alter_rooms_food_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room_type",
            name="name",
            field=models.CharField(
                choices=[("Shared room", "Shared room"), ("pvt room", "Private room")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="cap",
            field=models.ManyToManyField(to="home.capacity"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="food",
            field=models.ManyToManyField(to="home.food"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_type",
            field=models.ManyToManyField(to="home.room_type"),
        ),
    ]
