# Generated by Django 4.1.2 on 2022-10-19 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_alter_room_type_name_alter_rooms_cap_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="duration",
            field=models.CharField(
                choices=[
                    ("6 Months", "6 Months"),
                    ("1 Year", "1 Year"),
                    ("2 Years", "2 Years"),
                ],
                default="6 Months",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
