# Generated by Django 4.1.2 on 2022-10-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0009_rooms_duration_alter_rooms_room_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="rooms", name="room_image",),
    ]
