# Generated by Django 4.1.2 on 2022-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_rooms_room_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="room_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
