# Generated by Django 4.1.2 on 2022-10-26 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_remove_rooms_room_image_rooms_room_image1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rooms",
            name="room_image1",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_image2",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
        migrations.AlterField(
            model_name="rooms",
            name="room_image3",
            field=models.ImageField(null=True, upload_to="img/"),
        ),
    ]
