# Generated by Django 4.1.2 on 2022-10-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_rooms_room_image1_alter_rooms_room_image2_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rooms",
            name="lat",
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name="rooms",
            name="long",
            field=models.DecimalField(decimal_places=7, max_digits=11, null=True),
        ),
    ]
